export const PERMISSIONS = {
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_BRANCHES: "MANAGE_BRANCHES",
  MANAGE_LOCATIONS: "MANAGE_LOCATIONS",
  MANAGE_SHIPMENTS: "MANAGE_SHIPMENTS",
  MANAGE_PRICING: "MANAGE_PRICING",
  MANAGE_WALLET: "MANAGE_WALLET",
  VIEW_REPORTS: "VIEW_REPORTS",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LIST: Permission[] = Object.values(PERMISSIONS);
