export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  EMPLOYEE: "EMPLOYEE",
  USER_PERSONAL: "USER_PERSONAL",
  USER_BUSINESS: "USER_BUSINESS",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<Role, Role[]> = {
  SUPER_ADMIN: Object.values(ROLES),
  BRANCH_ADMIN: [
    ROLES.BRANCH_ADMIN,
    ROLES.EMPLOYEE,
    ROLES.USER_PERSONAL,
    ROLES.USER_BUSINESS,
  ],
  EMPLOYEE: [ROLES.EMPLOYEE],
  USER_PERSONAL: [ROLES.USER_PERSONAL],
  USER_BUSINESS: [ROLES.USER_BUSINESS],
};

export const DEFAULT_PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  MANAGE_BRANCHES: [ROLES.SUPER_ADMIN],
  CREATE_SHIPMENT: [
    ROLES.BRANCH_ADMIN,
    ROLES.EMPLOYEE,
    ROLES.USER_PERSONAL,
    ROLES.USER_BUSINESS,
  ],
  VIEW_WALLET: [
    ROLES.SUPER_ADMIN,
    ROLES.BRANCH_ADMIN,
    ROLES.USER_PERSONAL,
    ROLES.USER_BUSINESS,
  ],
  MANAGE_PRICING: [ROLES.SUPER_ADMIN],
};
